@startuml diagram


class Character{
    +characterName: string
    +characterPrefab: GameObject
    +health: Health
    +energy: Energy
    +healthBar: HealthBar
    +energyBar: EnergyBar

    +Grapple()
    +Attack()
    +Counter()
    +Dodge()
    +Heal()
    -UpdateHealthBar(health: Health)
    -UpdateEnergyBar(energy: Energy)
}


class BloodLustPlayer extends Player{
    -score: int
    -character: Character
    -isWinner: Boolean = false
    -hand: List<Card>
        
    +BloodLustPlayer(NickName: string, actorNumber: int, isLocal: Boolean)
    +generateCard()
    +SetScore(score: int)
    +GetScore(): int
    +SetWinner(isWinner: Boolean): void
    +IsWinner(): Boolean
}

class Card implements IComparable{
    +type: String
    +damageAmount: int
    +artwork: Sprite
    +CompareTo(anotherCharacter: Character): int

}

class Energy{
    -maxEnergy: int
    -currentEnergy: int

    +AddSkillPoints(combo: int)
}

class Health{
    +maxHealth: int
    +currentHealth: int
    +ReduceHealth(damageAmount: int)
    +Heal(healAmount: int)
}

class EnergyBar{
    +energy: Energy
    +fillImage: Image
    +slider: Slider
}

class HealthBar{
    +health: Health
    +fillImage: Image
    +slider: Slider
    +colour: Colour
}

class GameManager{
    
    -Start()
    -Update()
    +HandleCardSelection()
    +CompareCardTypes()
    +CompareDamage(): int
    
}

BloodLustPlayer --> Character: uses
Health --> HealthBar: uses
Energy --> EnergyBar: uses
Energy -right- Health: associated with
Player -left-> Card: uses


@enduml
